name: Tuner
options:
  bundleIdPrefix: com.jgreco
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: V6JPQCD336
targets:
  Tuner:
    type: application
    platform: iOS
    sources:
      - Tuner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jgreco.tuner
        PRODUCT_NAME: Tuner
        INFOPLIST_FILE: Tuner/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  TunerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TunerTests
    dependencies:
      - target: Tuner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jgreco.tuner.tests
        GENERATE_INFOPLIST_FILE: YES
